### ISSUE TITLE
compile problem please help

### ISSUE THREAD

**Issue by Keskebeu** [Travisholt92/android_kernel_lge_lv517#1]
No rule to make target 'arch/x86/mm/memtest.o', needed by 'arch/x86/mm/built-in.o'.  Stop.

4.6 cross compile. ubuntu 16.04

**Comment by Travisholt92** [comment]
Use sd4xx-common for anything other than stock instead of the lv517 kernel

**Comment by Keskebeu** [comment]
That's the one I was looking for (lineage 14.1) thanks.
